[package]
name = "petratools"
version = "0.1.0"
authors = ["Erin Moon <erin@hecke.rs>"]
edition = "2018"

[features]
trace = ["peg/trace"]

[dependencies]
structopt = "0.3"
color-eyre = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
peg = "0.7"
kiss3d = "0.32.0"
ultraviolet = "0.8.1"
